# Generated by Django 3.2.16 on 2022-12-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221229_1021'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='posts_follow_prevent_self_follow',
        ),
    ]
